// Barrel re-export — original data extracted to src/data/ modules
export {
  CHARACTER_COLORS, SKIN_TONES, HAIR_STYLES, EYE_COLORS,
  ARMOR_STYLES, HELMET_STYLES, VISOR_STYLES, SHOULDER_STYLES,
  BADGES, WEAPON_SKINS, LOADOUT_CLASSES, BACKSTORIES, VOICE_PROFILES,
  DEFAULT_CHARACTER,
  gearBonuses,
  GEAR_SLOTS,
  ARIA_COMMS,
  WALL_COLORS,
  TUTORIAL_MAP,
  ARENA_MAPS, ARENA_MAP,
  CAMPAIGN_LEVELS,
  WEAPONS,
  ENEMY_TYPES,
  UPGRADES,
  ACHIEVEMENT_ICON_SVGS, ACHIEVEMENTS,
} from '../src/data/index.js';
