// Barrel re-export — original data extracted to src/data/ modules
export {
  CUTSCENE_SCRIPTS,
  CHARACTER_COLORS, ARMOR_STYLES, BADGES, WEAPON_SKINS, LOADOUT_CLASSES, DEFAULT_CHARACTER,
  ARIA_COMMS,
  WALL_COLORS,
  TUTORIAL_MAP,
  ARENA_MAPS, ARENA_MAP,
  CAMPAIGN_LEVELS,
  WEAPONS,
  ENEMY_TYPES,
  UPGRADES,
  ACHIEVEMENT_ICON_SVGS, ACHIEVEMENTS,
} from '../src/data/index.js';
